<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '3.13.1';
$moduleRevision = '9d307cec89f8125022960023426dd6e83f6d1c1b';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/Resellers_Center_For_WHMCS';